{
 "title": "Mongo",
 "description": "MongoDB dashboard based on graphite data-source and telegraf collector. Focused on replica set.\n\n\nCredit to https://grafana.com/orgs/saada who dashboard was the starting guide to this but using a different datasource: https://grafana.com/dashboards/2583",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "region", "query": "prd,uat,tst" }
  ]
 },
 "panels": [
  {
   "title": "Query Metrics for $region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "dataEnv",
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.queries_per_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Commands Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.commands_per_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Deletes Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.deletes_per_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "GetMore Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.getmores_per_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Inserts Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.inserts_per_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Updates Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.updates_per_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica Set Metrics for $region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "env",
   "targets": [
    {}
   ]
  },
  {
   "title": "$region-mongo0",
   "type": "stat",
   "description": "Replica State",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(infrastructure.*.$region*.$region-mongo0*.mongodb.*.replica_set_member_state, 5)"
    }
   ]
  },
  {
   "title": "$region-mongo1",
   "type": "stat",
   "description": "Replica State",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(infrastructure.*.$region*.$region-mongo1*.mongodb.*.replica_set_member_state, 5)"
    }
   ]
  },
  {
   "title": "$region-mongo2",
   "type": "stat",
   "description": "Replica State",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(infrastructure.*.$region*.$region-mongo2*.mongodb.*.replica_set_member_state, 5)"
    }
   ]
  },
  {
   "title": "Replica Query Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.mongodb.*.repl_queries_per_sec, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica Inserts Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.mongodb.*.repl_inserts_per_sec, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica Commands Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.mongodb.*.repl_commands_per_sec, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica Deletes Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.mongodb.*.repl_deletes_per_sec, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica GetMores Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.mongodb.*.repl_getmores_per_sec, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica Updates Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.mongodb.*.repl_updates_per_sec, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replication Oplog Window",
   "type": "graph",
   "description": "The time difference between the oldest and newest entries in the oplog. That’s the amount of time an operation will remain in the oplog before being overwritten by a new entry.\n\nFirstly, your replication oplog window tells you how long a secondary member can be offline and still catch up to the primary without doing a full resync\n\nThe second, and more subtle, issue is that replication oplog window is also the maximum amount of time it can take to perform the initial phase of a full sync (either when adding a new secondary, or fully resyncing a stale one)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.repl_oplog_window_sec, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Replica set member state",
   "type": "graph",
   "description": "If state move out of range 1:2 then will alert\nEach value maps to a state see:",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.prd_data.prd-mongo0*.mongodb.*.replica_set_member_state, 5), '.*_data.(.*?)_.*', '\\1')"
    },
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.prd_data.prd-mongo1*.mongodb.*.replica_set_member_state, 5), '.*_data.(.*?)_.*', '\\1')"
    },
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.*.prd_data.prd-mongo2*.mongodb.*.replica_set_member_state, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mem.used_percent, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.net_in_bytes, 10), '.*_data\\.([^_]*?)_.*(net.*?)\\)', '\\1-\\2')"
    },
    {
     "expr": "rate(mongodb_network_bytes_total{instance=~\"$env\"}[$interval])",
     "legendFormat": "{{state}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.net_out_bytes, 10), '.*_data\\.([^_]*?)_.*(net.*?)\\)', '\\1-\\2')"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_replset_oplog_size_bytes{instance=~\"$env\"}",
     "legendFormat": "{{type}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.$region*.$region-mongo*.mongodb.*.open_connections, 10), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "5 Min Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(keepLastValue(infrastructure.*.$region*.$region-mongo*.system.load5, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Replication Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.prd_data.prd-mongo*.mongodb.*.repl_lag, 5), '.*_data.(.*?)_.*', '\\1')"
    },
    {
     "expr": "rate(mongodb_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.uat_data.uat-mongo*.mongodb.*.repl_lag, 5), '.*_data.(.*?)_.*', '\\1')"
    },
    {
     "expr": "rate(mongodb_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}",
     "target": "aliasSub(keepLastValue(infrastructure.eu-west-1.tst_data.tst-mongo*.mongodb.*.repl_lag, 5), '.*_data.(.*?)_.*', '\\1')"
    }
   ]
  },
  {
   "title": "Disk IO Utilization (prd only)",
   "type": "graph",
   "description": "Hardcoded to show prd, alerts dont work with template variables.\n\nFor reference on getting percent value:",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000 or irate(node_disk_io_time_ms{instance=~\"shr.*\"}[5m])/1000)",
     "legendFormat": "{{device}} - {{instance}}",
     "target": "aliasSub(asPercent(perSecond(infrastructure.eu-west-1.prd_data.prd-mongo*.diskio.*.io_time), 1000), '.*_data\\.([^_]*?)_.*diskio\\.([^.]*).*', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Reads Completed (Per Second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed{instance=~\"shr.*\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}",
     "target": "aliasSub(perSecond(infrastructure.eu-west-1.$region*.$region-mongo*.diskio.*.reads), '.*_data\\.([^_]*?)_.*diskio\\.([^.]*).*', '\\1 \\2')"
    }
   ]
  },
  {
   "title": "Disk Writes Completed (Per Second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed{instance=~\"shr.*\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}",
     "target": "aliasSub(perSecond(infrastructure.eu-west-1.$region*.$region-mongo*.diskio.*.writes), '.*_data\\.([^_]*?)_.*diskio\\.([^.]*).*', '\\1 \\2')"
    }
   ]
  }
 ]
}