# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: docker
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: prometheus

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: node-exporter

    scrape_interval: 5s

    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: elasticsearch
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_labels: true
    static_configs:
    - targets: ['elastic_search-exporter:9114']

  - job_name: mongodb
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_labels: true
    static_configs:
      - targets: ['mongo-exporter:9001']

  - job_name: mongodb_query
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_labels: true
    static_configs:
      - targets: ['mongo-query-exporter:9412']

  - job_name: cadvisor
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          group: 'cadvisor'