# docker compose -f ./elastic-kibana.yml -p elastic-kibana up -d

version: '3.8'

volumes:
  es_data:
    driver: local

networks:
  devnet:
    external: true

services:
  elastic_search:
    image: elasticsearch:8.3.3
    container_name: elasticsearch
    restart: "unless-stopped"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
      # - xpack.monitoring.enabled='false'
      # - xpack.watcher.enabled='false'
      # - xpack.ml.enabled='false'
      # - http.cors.enabled='true'
      # - http.cors.allow-origin="*"
      # - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
      # - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type, Content-Length
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elastic_search.rule=Host(`elasticsearch.localhost`)"
      - "traefik.http.routers.elastic_search.entrypoints=web"
    networks:
      - devnet

  elastic_search_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: elastic_search-exporter
    restart: "unless-stopped"
    ports:
      - 9114:9114
    command:
     - '--es.uri=http://elasticsearch:9200'
    depends_on:
      - elastic_search
    networks:
      - devnet

  elastichq:
    hostname: elastichq
    container_name: elastichq
    restart: "unless-stopped"
    image: "elastichq/elasticsearch-hq"
    ports:
      - 4000:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elastichq.rule=Host(`elastichq.localhost`)"
      - "traefik.http.routers.elastichq.entrypoints=web"
    depends_on:
      - elastic_search
    networks:
      - devnet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.3.3
    restart: "unless-stopped"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      bootstrap.memory_lock: true
      # XPACK_GRAPH_ENABLED: false
      # XPACK_ML_ENABLED: false
      # XPACK_REPORTING_ENABLED: false
      # XPACK_SECURITY_ENABLED: false
      # XPACK_WATCHER_ENABLED: false
    ports:
      - 5601:5601
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.tls=false"
      - "traefik.http.routers.kibana.rule=Host(`kibana.localhost`)"
    depends_on:
      - elastic_search
    networks:
      - devnet