# docker compose -f ./redis.yml -p redis up -d

version: '3.8'

networks:
  devnet:
    external: true

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
       - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - devnet

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: "redis:6379"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - devnet